export const styles = {
    page: {
        fontFamily: 'Inter, sans-serif',
        display: 'flex',
        flexDirection: 'column',
        gap: '32px',
        minHeight: '100vh',
        width: '100%',
        maxWidth: '1200px',
        padding: '32px clamp(20px, 4vw, 56px)',
        boxSizing: 'border-box',
        background: 'linear-gradient(180deg, #f7fdf9 0%, #ffffff 60%)',
        overflowX: 'hidden',
        paddingBottom: '110px',
        margin: '0 auto',
    },
    notificationContainer: {
        position: 'fixed',
        top: '20px',
        right: '20px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        zIndex: 20,
    },
    notification: {
        backgroundColor: '#fff',
        padding: '12px 18px',
        borderRadius: '12px',
        boxShadow: '0 10px 30px rgba(0,0,0,0.12)',
        borderLeft: '5px solid #16a34a',
        fontWeight: 500,
        color: '#0b3b24',
    },
    loadingOverlay: {
        position: 'fixed',
        inset: 0,
        backgroundColor: 'rgba(255,255,255,0.85)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '12px',
        zIndex: 15,
        fontWeight: 600,
        color: '#0b3b24',
    },
    loadingSpinner: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        border: '4px solid rgba(20,83,45,0.2)',
        borderTopColor: '#16a34a',
        animation: 'userPageSpin 1s linear infinite',
    },
    hero: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
        gap: '32px',
        alignItems: 'center',
    },
    heroBadge: {
        display: 'inline-block',
        padding: '6px 14px',
        borderRadius: '999px',
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        color: '#0f8346',
        fontWeight: 600,
        marginBottom: '12px',
        fontSize: '0.85rem',
    },
    heroTitle: {
        fontSize: 'clamp(1.8rem, 3vw, 2.6rem)',
        margin: '0 0 10px',
        color: '#082b16',
    },
    heroSubtitle: {
        margin: '0 0 20px',
        color: '#4b5b52',
        lineHeight: 1.5,
    },
    heroMeta: {
        display: 'flex',
        gap: '12px',
        flexWrap: 'wrap',
        marginBottom: '18px',
    },
    heroMetaChip: {
        padding: '10px 16px',
        borderRadius: '999px',
        backgroundColor: '#f0fdf4',
        border: '1px solid rgba(22,163,74,0.25)',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    heroMetaChipLabel: {
        fontSize: '0.75rem',
        color: '#4b5b52',
    },
    heroActions: {
        display: 'flex',
        gap: '12px',
        flexWrap: 'wrap',
    },
    ctaButton: {
        padding: '12px 28px',
        borderRadius: '999px',
        border: 'none',
        background: 'linear-gradient(120deg, #16a34a, #22d3ee)',
        color: '#fff',
        fontWeight: 600,
        cursor: 'pointer',
        transition: 'opacity .2s ease',
    },
    secondaryGhost: {
        padding: '12px 20px',
        borderRadius: '999px',
        border: '1px solid rgba(8, 43, 22, 0.2)',
        background: 'transparent',
        color: '#0f172a',
        cursor: 'pointer',
    },
    heroStats: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: '16px',
    },
    heroStatCard: {
        padding: '20px',
        borderRadius: '20px',
        backgroundColor: '#fff',
        boxShadow: '0 15px 30px rgba(15, 118, 110, 0.1)',
    },
    heroStatLabel: { margin: 0, color: '#6b7a70', fontSize: '0.85rem' },
    heroStatValue: { margin: '6px 0 0', fontSize: '1.8rem', color: '#0c4a34' },
    heroStatFoot: { margin: '4px 0 0', color: '#8da396', fontSize: '0.8rem' },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '18px',
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: '18px',
        padding: '20px',
        boxShadow: '0 10px 25px rgba(0,0,0,0.05)',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    cardTitle: {
        margin: 0,
        color: '#0b3b24',
        fontSize: '1rem',
    },
    statusText: {
        margin: 0,
        fontSize: '1rem',
        lineHeight: 1.4,
    },
    cardHint: {
        margin: 0,
        fontSize: '0.85rem',
        color: '#7a8a80',
    },
    cardBody: {
        margin: 0,
        color: '#4b5b52',
        lineHeight: 1.5,
    },
    smallButton: {
        alignSelf: 'flex-start',
        padding: '10px 18px',
        borderRadius: '999px',
        border: '1px solid rgba(15, 118, 110, 0.3)',
        background: 'transparent',
        cursor: 'pointer',
    },
    mapSection: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        marginBottom: '24px',
    },
    mapHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        gap: '12px',
        flexWrap: 'wrap',
        alignItems: 'center',
    },
    mapEyebrow: {
        margin: 0,
        textTransform: 'uppercase',
        letterSpacing: '0.15em',
        fontSize: '0.75rem',
        color: '#8da396',
    },
    mapTitle: { margin: '4px 0 0', color: '#0b3b24', fontSize: '1.3rem' },
    mapCard: {
        backgroundColor: '#fff',
        borderRadius: '24px',
        padding: '20px',
        boxShadow: '0 20px 35px rgba(0,0,0,0.08)',
        width: '100%',
    },
    map: {
        height: 'calc(50vh - 60px)',
        width: '100%',
        borderRadius: '18px',
        overflow: 'hidden',
    },
    mapInfo: {
        marginTop: '16px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '16px',
        flexWrap: 'wrap',
    },
    mapInfoLabel: { margin: 0, fontSize: '0.8rem', color: '#7a8a80' },
    mapInfoValue: { margin: '4px 0 0', fontSize: '1rem', color: '#0c4a34' },
    requestButton: {
        padding: '12px 22px',
        borderRadius: '12px',
        border: 'none',
        backgroundColor: '#0ea5e9',
        color: '#fff',
        fontWeight: 600,
        cursor: 'pointer',
    },
    requestActions: {
        display: 'flex',
        gap: '12px',
        marginTop: '16px',
    },
    secondaryButton: {
        backgroundColor: '#eef5f0',
        color: '#0b3b24',
        border: 'none',
        padding: '12px 18px',
        borderRadius: '12px',
        cursor: 'pointer',
    },
    navButton: {
        background: 'none',
        border: 'none',
        color: '#333',
        cursor: 'pointer',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '4px',
        fontSize: '0.75rem',
    },
    navButtonActive: {
        background: 'none',
        border: 'none',
        color: '#4CAF50',
        cursor: 'pointer',
        fontWeight: 'bold',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '4px',
        fontSize: '0.75rem',
    },
    navIcon: {
        fontSize: '1.5rem',
    },
    mapHint: {
        margin: '4px 0 0',
        color: '#7a8a80',
        fontSize: '0.85rem',
    },
    locationError: {
        color: '#d14343',
        marginTop: '8px',
        fontSize: '0.85rem',
    },
    activityPanel: {
        backgroundColor: '#fff',
        borderRadius: '20px',
        padding: '24px',
        boxShadow: '0 10px 20px rgba(0,0,0,0.05)',
    },
    rewardsPanel: {
        backgroundColor: '#fff',
        borderRadius: '20px',
        padding: '24px',
        boxShadow: '0 10px 20px rgba(0,0,0,0.05)',
    },
    rewardsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
        gap: '16px',
    },
    rewardCard: {
        padding: '20px',
        borderRadius: '16px',
        backgroundColor: '#f9fafb',
        border: '1px solid #e5e7eb',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    rewardName: {
        margin: 0,
        fontSize: '1.1rem',
        color: '#0b3b24',
    },
    rewardPoints: {
        fontSize: '0.9rem',
        fontWeight: 600,
        color: '#0ea5e9',
    },
    redeemButton: {
        padding: '10px 16px',
        borderRadius: '8px',
        border: 'none',
        backgroundColor: '#16a34a',
        color: '#fff',
        cursor: 'pointer',
        fontWeight: 600,
    },
    redeemButtonDisabled: {
        backgroundColor: '#d1d5db',
        color: '#6b7280',
        cursor: 'not-allowed',
    },
    tabHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '20px',
    },
    sectionTitle: {
        margin: '0 0 8px',
        fontSize: '1.5rem',
        color: '#0b3b24',
    },
    activityTotal: {
        fontSize: '0.9rem',
        color: '#6b7280',
    },
    activityList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    activityItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        padding: '16px',
        borderRadius: '12px',
        backgroundColor: '#f9fafb',
    },
    activityIcon: {
        fontSize: '1.5rem',
    },
    activityDetails: {
        flex: 1,
    },
    activityTitle: {
        margin: 0,
        fontSize: '1rem',
        color: '#0b3b24',
    },
    activityMeta: {
        margin: '4px 0',
        fontSize: '0.85rem',
        color: '#6b7280',
    },
    activityPoints: {
        fontSize: '0.9rem',
        fontWeight: 600,
    },
    profilePanel: {
        backgroundColor: '#fff',
        borderRadius: '20px',
        padding: '24px',
        boxShadow: '0 10px 20px rgba(0,0,0,0.05)',
    },
    profileRows: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        marginBottom: '24px',
    },
    profileRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '12px 0',
        borderBottom: '1px solid #e5e7eb',
    },
    profileStats: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
        gap: '16px',
    },
    profileStatCard: {
        textAlign: 'center',
        padding: '16px',
        borderRadius: '12px',
        backgroundColor: '#f9fafb',
    },
    input: {
        padding: '8px 12px',
        borderRadius: '6px',
        border: '1px solid #d1d5db',
        fontSize: '1rem',
        width: '200px',
    },
    navBar: {
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        height: '70px',
        backgroundColor: '#fff',
        display: 'flex',
        justifyContent: 'space-around',
        alignItems: 'center',
        boxShadow: '0 -6px 20px rgba(15, 23, 42, 0.08)',
        zIndex: 10,
    },
};
