export const styles = {
    page: {
        fontFamily: 'Inter, sans-serif',
        minHeight: '100vh',
        background: 'linear-gradient(180deg, #f0fdf4 0%, #ffffff 70%)',
        padding: '32px clamp(16px, 4vw, 56px)',
        boxSizing: 'border-box',
        display: 'flex',
        flexDirection: 'column',
        gap: '32px',
    },
    hero: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
        gap: '24px',
        alignItems: 'center',
    },
    heroBadge: {
        display: 'inline-block',
        padding: '6px 14px',
        borderRadius: '999px',
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        color: '#047857',
        fontWeight: 600,
        fontSize: '0.85rem',
        marginBottom: '12px',
    },
    heroTitle: {
        margin: '0 0 10px',
        fontSize: 'clamp(1.8rem, 3vw, 2.5rem)',
        color: '#064e3b',
    },
    heroSubtitle: {
        margin: '0 0 18px',
        color: '#4b5563',
        lineHeight: 1.5,
    },
    heroActions: {
        display: 'flex',
        gap: '12px',
        flexWrap: 'wrap',
    },
    heroButton: {
        padding: '10px 20px',
        borderRadius: '999px',
        border: '1px solid rgba(6, 78, 59, 0.2)',
        background: '#ffffff',
        color: '#064e3b',
        cursor: 'pointer',
    },
    heroButtonActive: {
        padding: '10px 20px',
        borderRadius: '999px',
        border: 'none',
        background: 'linear-gradient(120deg, #10b981, #22d3ee)',
        color: '#fff',
        cursor: 'pointer',
    },
    profileCard: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        backgroundColor: '#ffffff',
        borderRadius: '18px',
        padding: '16px 20px',
        boxShadow: '0 10px 25px rgba(22, 163, 74, 0.18)',
    },
    profileAvatar: { width: 56, height: 56, borderRadius: '50%', cursor: 'pointer' },
    profileName: { margin: 0, color: '#0f172a' },
    profileStatus: { margin: 0, color: '#64748b', fontSize: '0.85rem' },
    statsGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '16px',
    },
    statCard: {
        backgroundColor: '#ffffff',
        borderRadius: '16px',
        padding: '18px',
        boxShadow: '0 10px 20px rgba(22, 163, 74, 0.12)',
    },
    statLabel: { margin: 0, color: '#64748b', fontSize: '0.85rem' },
    statValue: { margin: '6px 0 0', fontSize: '1.8rem', color: '#0f172a' },
    statFoot: { margin: '4px 0 0', color: '#94a3b8', fontSize: '0.85rem' },
    layout: {
        display: 'grid',
        gridTemplateColumns: 'minmax(0, 2fr) minmax(280px, 1fr)',
        gap: '24px',
        alignItems: 'flex-start',
    },
    mapCard: {
        backgroundColor: '#ffffff',
        borderRadius: '24px',
        padding: '20px',
        boxShadow: '0 20px 35px rgba(22, 163, 74, 0.15)',
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    cardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        gap: '12px',
        flexWrap: 'wrap',
        alignItems: 'center',
    },
    cardEyebrow: {
        margin: 0,
        fontSize: '0.75rem',
        textTransform: 'uppercase',
        letterSpacing: '0.18em',
        color: '#94a3b8',
    },
    cardTitle: { margin: '4px 0 0', color: '#0f172a' },
    cardActions: { display: 'flex', gap: '12px', flexWrap: 'wrap' },
    ghostButton: {
        padding: '10px 18px',
        borderRadius: '12px',
        border: '1px solid rgba(6, 95, 70, 0.25)',
        background: '#f0fdf4',
        cursor: 'pointer',
    },
    primaryButton: {
        backgroundColor: '#10b981',
        color: '#ffffff',
        border: 'none',
        padding: '10px 16px',
        borderRadius: '12px',
        cursor: 'pointer',
    },
    mapWrapper: {
        borderRadius: '18px',
        overflow: 'hidden',
        width: '100%',
    },
    map: {
        width: '100%',
        minHeight: '360px',
    },
    mapHint: {
        margin: 0,
        color: '#64748b',
        fontSize: '0.85rem',
    },
    recenterButton: {
        position: 'absolute',
        top: '10px',
        right: '10px',
        zIndex: 1000,
        backgroundColor: '#ffffff',
        border: 'none',
        borderRadius: '8px',
        padding: '8px 12px',
        cursor: 'pointer',
        boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
        fontSize: '1.2rem',
    },
    sidePanel: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    stopCard: {
        backgroundColor: '#ecfdf5',
        borderRadius: '18px',
        padding: '18px',
        border: '1px solid #bbf7d0',
    },
    stopTitle: { margin: '4px 0', color: '#064e3b' },
    stopMeta: { margin: 0, color: '#6b7280', fontSize: '0.9rem' },
    stopActions: { display: 'flex', gap: '10px', marginTop: '12px' },
    successButton: {
        flex: 1,
        backgroundColor: '#16a34a',
        border: 'none',
        color: '#fff',
        padding: '10px',
        borderRadius: '10px',
        cursor: 'pointer',
    },
    failButton: {
        flex: 1,
        backgroundColor: '#ef4444',
        border: 'none',
        color: '#fff',
        padding: '10px',
        borderRadius: '10px',
        cursor: 'pointer',
    },
    historyCard: {
        backgroundColor: '#ffffff',
        borderRadius: '16px',
        padding: '16px',
        boxShadow: '0 10px 20px rgba(22,163,74,0.12)',
    },
    queueCard: {
        backgroundColor: '#ffffff',
        borderRadius: '16px',
        padding: '16px',
        boxShadow: '0 10px 20px rgba(15,23,42,0.05)',
    },
    cardHeaderRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    queueBadge: {
        backgroundColor: '#dcfce7',
        color: '#047857',
        padding: '4px 10px',
        borderRadius: '999px',
        fontSize: '0.8rem',
    },
    queueList: {
        listStyle: 'none',
        margin: '12px 0 0',
        padding: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    queueItem: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '12px',
        borderRadius: '12px',
        backgroundColor: '#ecfdf5',
    },
    queueId: { margin: 0, color: '#0f172a', fontWeight: 600 },
    queueCoords: { margin: 0, color: '#475569', fontSize: '0.85rem' },
    queueStatus: { color: '#475569', fontSize: '0.85rem', textTransform: 'capitalize' },
    jobCard: {
        backgroundColor: '#ffffff',
        borderRadius: '16px',
        padding: '18px',
        boxShadow: '0 12px 24px rgba(22,163,74,0.16)',
    },
    jobCardMuted: {
        backgroundColor: '#f0fdf4',
        borderRadius: '16px',
        padding: '18px',
        border: '1px dashed #bbf7d0',
    },
    timer: {
        backgroundColor: '#f97316',
        color: '#ffffff',
        padding: '4px 10px',
        borderRadius: '999px',
        fontSize: '0.8rem',
    },
    jobMeta: {
        margin: '6px 0 0',
        color: '#475569',
        fontSize: '0.9rem',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
    },
    modalContent: {
        backgroundColor: '#ffffff',
        borderRadius: '20px',
        padding: '24px',
        maxWidth: '400px',
        width: '90%',
        boxShadow: '0 20px 35px rgba(0,0,0,0.15)',
    },
    modalTitle: {
        margin: '0 0 20px',
        color: '#0f172a',
        textAlign: 'center',
    },
    iconGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: '16px',
        marginBottom: '20px',
    },
    iconOption: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '12px',
        borderRadius: '12px',
        backgroundColor: '#f9fafb',
        border: '2px solid transparent',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    iconOptionSelected: {
        border: '2px solid #10b981',
        backgroundColor: '#ecfdf5',
    },
    iconPreview: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        marginBottom: '8px',
    },
    iconLabel: {
        fontSize: '0.8rem',
        color: '#64748b',
        textTransform: 'capitalize',
    },
    closeButton: {
        width: '100%',
        padding: '12px',
        borderRadius: '12px',
        border: 'none',
        backgroundColor: '#ef4444',
        color: '#ffffff',
        cursor: 'pointer',
        fontWeight: 600,
    },
};
