export const styles = {
    container: {
        display: 'flex',
        minHeight: '100vh',
        backgroundColor: '#f0fdf4',
        fontFamily: 'Inter, sans-serif',
        color: '#022c22',
    },
    sidebar: {
        width: '260px',
        backgroundColor: '#022c22',
        color: '#ecfdf5',
        display: 'flex',
        flexDirection: 'column',
        padding: '24px',
        flexShrink: 0,
    },
    logoArea: {
        marginBottom: '40px',
        paddingLeft: '12px',
    },
    logoText: {
        fontSize: '1.5rem',
        fontWeight: '700',
        color: '#10b981',
        margin: 0,
    },
    nav: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        flex: 1,
    },
    navItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '12px 16px',
        borderRadius: '12px',
        border: 'none',
        background: 'transparent',
        color: '#94a3b8',
        fontSize: '1rem',
        fontWeight: '500',
        cursor: 'pointer',
        transition: 'all 0.2s',
        textAlign: 'left',
    },
    navItemActive: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '12px 16px',
        borderRadius: '12px',
        border: 'none',
        background: '#064e3b',
        color: '#ecfdf5',
        fontSize: '1rem',
        fontWeight: '600',
        cursor: 'pointer',
        textAlign: 'left',
    },
    userProfile: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '16px',
        borderTop: '1px solid #1e293b',
        marginTop: 'auto',
    },
    avatar: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        backgroundColor: '#3b82f6',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
        color: '#fff',
    },
    userName: {
        margin: 0,
        fontWeight: '600',
        fontSize: '0.9rem',
    },
    userRole: {
        margin: 0,
        fontSize: '0.8rem',
        color: '#94a3b8',
    },
    main: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    header: {
        height: '80px',
        borderBottom: '1px solid #bbf7d0',
        backgroundColor: '#ecfdf5',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '0 clamp(16px, 4vw, 40px)',
    },
    pageTitle: {
        fontSize: '1.5rem',
        fontWeight: '700',
        margin: 0,
    },
    date: {
        color: '#64748b',
        fontWeight: '500',
    },
    contentArea: {
        flex: 1,
        padding: '24px clamp(16px, 4vw, 40px)',
        overflowY: 'auto',
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '24px',
    },
    statCard: {
        backgroundColor: '#fff',
        padding: '24px',
        borderRadius: '16px',
        boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)',
        display: 'flex',
        alignItems: 'center',
        gap: '20px',
    },
    iconBox: {
        width: '56px',
        height: '56px',
        borderRadius: '16px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    statLabel: {
        margin: '0 0 4px',
        color: '#64748b',
        fontSize: '0.9rem',
        fontWeight: '500',
    },
    statValue: {
        margin: 0,
        fontSize: '1.8rem',
        fontWeight: '700',
        color: '#022c22',
    },
    statSub: {
        margin: '4px 0 0',
        fontSize: '0.8rem',
        color: '#94a3b8',
    },
    activitySection: {
        gridColumn: '1 / -1',
        backgroundColor: '#fff',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)',
        marginTop: '24px',
    },
    sectionTitle: {
        fontSize: '1.2rem',
        fontWeight: '700',
        marginBottom: '20px',
    },
    activityList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    activityItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        paddingBottom: '16px',
        borderBottom: '1px solid #f1f5f9',
    },
    activityIcon: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        backgroundColor: '#f8fafc',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    activityText: {
        margin: '0 0 4px',
        fontSize: '0.95rem',
    },
    activityTime: {
        margin: 0,
        fontSize: '0.85rem',
        color: '#94a3b8',
    },
    mapContainer: {
        height: '600px',
        borderRadius: '16px',
        overflow: 'hidden',
        boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)',
    },
    reviewsPanel: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
    },
    filterBar: {
        display: 'flex',
        gap: '12px',
    },
    filterBtn: {
        padding: '8px 16px',
        borderRadius: '99px',
        border: '1px solid #e2e8f0',
        background: '#fff',
        color: '#64748b',
        cursor: 'pointer',
        fontWeight: '500',
    },
    filterBtnActive: {
        padding: '8px 16px',
        borderRadius: '99px',
        border: 'none',
        background: '#022c22',
        color: '#ecfdf5',
        cursor: 'pointer',
        fontWeight: '500',
    },
    ghostButton: {
        padding: '10px 18px',
        borderRadius: '12px',
        border: '1px solid rgba(6, 95, 70, 0.25)',
        background: '#f0fdf4',
        cursor: 'pointer',
    },
    primaryButton: {
        padding: '10px 18px',
        borderRadius: '12px',
        border: 'none',
        backgroundColor: '#10b981',
        color: '#ffffff',
        fontWeight: '600',
        cursor: 'pointer',
        fontSize: '0.95rem',
    },
    badge: {
        backgroundColor: '#ef4444',
        color: '#fff',
        padding: '2px 6px',
        borderRadius: '99px',
        fontSize: '0.75rem',
        marginLeft: '4px',
    },
    reviewsList: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
        gap: '20px',
    },
    reviewCard: {
        backgroundColor: '#fff',
        padding: '20px',
        borderRadius: '16px',
        border: '1px solid #e2e8f0',
    },
    reviewCardFlagged: {
        backgroundColor: '#fff',
        padding: '20px',
        borderRadius: '16px',
        border: '2px solid #fca5a5',
    },
    reviewHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '12px',
    },
    reviewerName: {
        fontWeight: '600',
    },
    stars: {
        display: 'flex',
        gap: '2px',
    },
    reviewComment: {
        color: '#475569',
        fontStyle: 'italic',
        marginBottom: '16px',
        lineHeight: '1.5',
    },
    reviewFooter: {
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: '0.85rem',
        color: '#94a3b8',
    },
    flagLabel: {
        marginTop: '12px',
        color: '#dc2626',
        fontWeight: '600',
        fontSize: '0.85rem',
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
    },
    emptyText: {
        color: '#94a3b8',
        fontStyle: 'italic',
    },
    placeholder: {
        textAlign: 'center',
        padding: '60px',
        color: '#94a3b8',
        fontSize: '1.2rem',
    },
    settingsPanel: {
        backgroundColor: '#fff',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)',
        maxWidth: '480px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
    },
    settingsLabel: {
        fontWeight: '600',
        marginBottom: '4px',
    },
    settingsSelect: {
        maxWidth: '320px',
        padding: '8px 12px',
        borderRadius: '8px',
        border: '1px solid #e2e8f0',
        fontSize: '0.95rem',
    },
    settingsHelp: {
        margin: '0 0 8px',
        color: '#64748b',
        fontSize: '0.9rem',
    },
    settingsCurrent: {
        marginTop: '8px',
        color: '#0f172a',
        fontSize: '0.9rem',
        fontWeight: '500',
    },
    usersPanel: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
    },
    panelHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '8px',
    },
    lastUpdated: {
        fontSize: '0.8rem',
        color: '#64748b',
    },
    filterSection: {
        display: 'flex',
        gap: '32px',
        flexWrap: 'wrap',
        alignItems: 'center',
    },
    filterGroup: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    filterLabel: {
        fontWeight: '600',
        color: '#374151',
        fontSize: '0.9rem',
    },
    listsContainer: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '24px',
    },
    listSection: {
        backgroundColor: '#fff',
        borderRadius: '16px',
        padding: '24px',
        boxShadow: '0 4px 6px -1px rgba(0,0,0,0.05)',
    },
    usersList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        maxHeight: '600px',
        overflowY: 'auto',
    },
    userCard: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '16px',
        border: '1px solid #e5e7eb',
        borderRadius: '12px',
        backgroundColor: '#fafafa',
    },
    userInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    userAvatar: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        backgroundColor: '#3b82f6',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#fff',
        fontWeight: 'bold',
        fontSize: '1.1rem',
    },
    workerAvatar: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        backgroundColor: '#10b981',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#fff',
        fontWeight: 'bold',
        fontSize: '1.1rem',
    },
    cardUserName: {
        margin: '0 0 4px',
        fontWeight: '600',
        color: '#111827',
    },
    userDetail: {
        margin: 0,
        fontSize: '0.85rem',
        color: '#6b7280',
    },
    userStatus: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: '4px',
    },
    statusBadge: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        padding: '4px 8px',
        borderRadius: '12px',
        fontSize: '0.8rem',
        fontWeight: '600',
    },
    lastActivity: {
        margin: 0,
        fontSize: '0.75rem',
        color: '#9ca3af',
    },
    loadingContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '60px',
        gap: '16px',
    },
    spinner: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        border: '4px solid rgba(16, 185, 129, 0.2)',
        borderTopColor: '#10b981',
        animation: 'userPageSpin 1s linear infinite',
    },
};
